services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: backenddb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: securepassword
    #ports:
    #  - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bfwa_network

  backend:
    build: ./backend
    depends_on:
      - db 
    ports:
      - "8482:8080"
    networks:
      - bfwa_network
      - container_app_network
    volumes: 
      - /home/mosh/hwdisk/projects/ImageOrganiser/frontend/data:/app/imagedir:rw 
    labels:
      - "traefik.enable=true" 
      - "traefik.http.routers.imageapi.entrypoints=websecure"
      - "traefik.http.routers.imageapi.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.imageapi.tls.certresolver=letsencrypt" 
      - "traefik.http.services.imageapi.loadbalancer.server.port=8080"
      - "traefik.docker.network=container_app_network" 

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "8480:80"
    networks:
      - bfwa_network
      - container_app_network 
    labels:
      - "traefik.enable=true" 
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/image`)"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt" 
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
      - "traefik.docker.network=container_app_network" 

networks:
  bfwa_network:
    driver: bridge
  container_app_network:
    external: true

volumes:
  postgres_data: